# Generated by Django 4.2 on 2023-05-10 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_invoice_product_profile_address_profile_bankaccount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='clientlist',
        ),
    ]
