# Generated by Django 4.2 on 2023-05-10 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_remove_client_clientlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='usercompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('address', models.TextField(default='this is a default message.')),
                ('code', models.IntegerField(blank=True, null=True)),
                ('vat', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='userpayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bankname', models.CharField(default='', max_length=50)),
                ('bankaccount', models.CharField(default='', max_length=50)),
                ('swift', models.CharField(blank=True, max_length=50, null=True)),
                ('vat', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='bankaccount',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='bankname',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='code',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='swift',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='vat',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='paydate',
            field=models.DateTimeField(),
        ),
    ]
