# Generated by Django 4.2 on 2023-05-12 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='subtotal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='tax',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
    ]
