# Generated by Django 4.2 on 2023-05-12 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0012_product_sumprice_product_sumtax_product_sumtotal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sumprice',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='sumtax',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='sumtotal',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True),
        ),
    ]
